#########################################################
# ElasticSearch Image without X-Pack
#########################################################
FROM docker.elastic.co/elasticsearch/elasticsearch:5.6.2

MAINTAINER Mehdi JrGr

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin remove x-pack --purge